/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Corkboard": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
    "CorkboardMedia": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "CorkboardNotifications": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "CorkboardRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "CorkboardUserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Corkboard_ThumbnailGenerate": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MyWeb": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}
