/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CDN": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Connections": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Media": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Notifications": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "PostWebSocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "Posts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Site": {
      "type": "sst.aws.SvelteKit"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}